import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Appointment } from '@/types';
import { format } from 'date-fns';
import { pt } from 'date-fns/locale';
import { supabase } from '@/integrations/supabase/client';

interface AppointmentModalProps { appointment: Appointment; isOpen: boolean; onClose: () => void; onEdit?: () => void; }
const AppointmentModal = ({ appointment, isOpen, onClose, onEdit }: AppointmentModalProps) => {
  const [cancelling, setCancelling] = useState(false); const [completing, setCompleting] = useState(false);
  if (!appointment) return null;
  const formatDate = (date: Date) => format(date, "dd 'de' MMMM 'de' yyyy", { locale: pt }); const formatTime = (date: Date) => format(date, 'HH:mm');
  const handleCancel = async () => { if (!window.confirm(`Tem certeza que deseja cancelar o agendamento de ${appointment.customer_name}?`)) return; setCancelling(true); const { error } = await supabase.from('appointments').update({ status: 'cancelled' }).eq('id', appointment.id).eq('user_id', appointment.user_id); setCancelling(false); if (error) { console.error(error); window.alert('Não foi possível cancelar o agendamento. Tente novamente.'); return; } onClose(); };
  const handleComplete = async () => { if (!window.confirm(`Marcar o atendimento de ${appointment.customer_name} como concluído?`)) return; setCompleting(true); const { error } = await supabase.from('appointments').update({ status: 'completed' }).eq('id', appointment.id).eq('user_id', appointment.user_id); setCompleting(false); if (error) { console.error(error); window.alert('Não foi possível concluir o agendamento. Tente novamente.'); return; } onClose(); };
  return <Dialog open={isOpen} onOpenChange={onClose}><DialogContent className="max-w-md"><DialogHeader><DialogTitle className="text-xl font-bold">Detalhes do Agendamento</DialogTitle></DialogHeader><div className="space-y-6 mt-4"><div><h3 className="text-lg font-semibold text-kendrah-purple">{appointment.service_name}</h3><div className="flex items-center mt-2"><span className="text-kendrah-purple/70 mr-2">📅</span><span>{formatDate(new Date(appointment.start_time))}</span></div><div className="flex items-center mt-2"><span className="text-kendrah-purple/70 mr-2">◷</span><span>{formatTime(new Date(appointment.start_time))} - {formatTime(new Date(appointment.end_time))}</span></div></div><div className="border-t border-border pt-4"><h4 className="text-sm uppercase text-muted-foreground mb-2">Cliente</h4><div className="font-medium">{appointment.customer_name}</div><div className="mt-2 text-muted-foreground">{appointment.customer_email}</div><div className="mt-2 text-muted-foreground">{appointment.customer_phone}</div></div>{appointment.notes && <div className="border-t border-border pt-4"><h4 className="text-sm uppercase text-muted-foreground mb-2">Observações</h4><p className="text-muted-foreground">{appointment.notes}</p></div>}<div className="border-t border-border pt-4 flex items-center justify-between gap-3"><span className={`inline-block px-3 py-1 rounded-full text-xs ${appointment.status === 'confirmed' ? 'bg-green-500/10 text-green-500' : appointment.status === 'pending' ? 'bg-yellow-500/10 text-yellow-500' : appointment.status === 'cancelled' ? 'bg-red-500/10 text-red-500' : 'bg-blue-500/10 text-blue-500'}`}>{appointment.status === 'confirmed' ? 'Confirmado' : appointment.status === 'pending' ? 'Pendente' : appointment.status === 'cancelled' ? 'Cancelado' : 'Concluído'}</span><div className="flex flex-wrap justify-end gap-2">{appointment.status !== 'cancelled' && appointment.status !== 'completed' && <Button variant="outline" className="text-green-600 border-green-500/30 hover:bg-green-500/10" onClick={handleComplete} disabled={completing}>{completing ? 'Concluindo...' : 'Concluir atendimento'}</Button>}{appointment.status !== 'cancelled' && appointment.status !== 'completed' && <Button variant="outline" className="text-red-600 border-red-500/30 hover:bg-red-500/10" onClick={handleCancel} disabled={cancelling}>{cancelling ? 'Cancelando...' : 'Cancelar agendamento'}</Button>}<Button variant="outline" className="text-kendrah-purple border-kendrah-purple/40 hover:bg-kendrah-purple/10" onClick={onEdit}>Editar</Button><Button className="bg-kendrah-purple hover:bg-kendrah-purple/90">Enviar Lembrete</Button></div></div></div></DialogContent></Dialog>;
}; export default AppointmentModal;
