import { useState, useCallback, useEffect } from 'react';
import { useIsMobile } from '@/hooks/use-mobile';
import { Calendar, momentLocalizer, Views } from 'react-big-calendar';
import moment from 'moment'; import 'moment/locale/pt-br'; import 'react-big-calendar/lib/css/react-big-calendar.css';
import { Appointment, CalendarEvent } from '@/types'; import AppointmentModal from './AppointmentModal'; import NewAppointmentDialog from './NewAppointmentDialog';

moment.locale('pt-br'); const localizer = momentLocalizer(moment);
const diasSemana = ['domingo','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado']; const diasSemanaAbrev = ['dom','seg','ter','qua','qui','sex','sáb']; const meses = ['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
const messages = { allDay:'Dia inteiro', previous:'Anterior', next:'Próximo', today:'Hoje', month:'Mês', week:'Semana', day:'Dia', agenda:'Lista', date:'Data', time:'Horário', event:'Agendamento', noEventsInRange:'Nenhum agendamento neste período.', showMore:(total:number)=>`+${total} agendamento${total===1?'':'s'}` };
const formats = { dateFormat:'DD/MM/YYYY', dayFormat:(date:Date)=>`${diasSemanaAbrev[date.getDay()]} ${String(date.getDate()).padStart(2,'0')}`, weekdayFormat:(date:Date)=>diasSemanaAbrev[date.getDay()], timeGutterFormat:'HH:mm', eventTimeRangeFormat:({start,end}:{start:Date;end:Date})=>`${moment(start).format('HH:mm')} – ${moment(end).format('HH:mm')}`, agendaTimeFormat:'HH:mm', agendaDateFormat:(date:Date)=>`${diasSemanaAbrev[date.getDay()]}, ${String(date.getDate()).padStart(2,'0')}/${String(date.getMonth()+1).padStart(2,'0')}`, monthHeaderFormat:(date:Date)=>`${meses[date.getMonth()]} de ${date.getFullYear()}`, dayHeaderFormat:(date:Date)=>`${diasSemana[date.getDay()]}, ${String(date.getDate()).padStart(2,'0')} de ${meses[date.getMonth()]} de ${date.getFullYear()}`, dayRangeHeaderFormat:({start,end}:{start:Date;end:Date})=>`${String(start.getDate()).padStart(2,'0')}/${String(start.getMonth()+1).padStart(2,'0')} – ${String(end.getDate()).padStart(2,'0')}/${String(end.getMonth()+1).padStart(2,'0')}/${end.getFullYear()}` };
interface Props { events: CalendarEvent[]; onEventClick?: (event:CalendarEvent)=>void; onUpdated?:()=>void; }
const AppointmentCalendar = ({events,onEventClick,onUpdated}:Props) => { const isMobile=useIsMobile(); const [view,setView]=useState(isMobile?Views.DAY:Views.WEEK); const [date,setDate]=useState(new Date()); const [selectedEvent,setSelectedEvent]=useState<CalendarEvent|null>(null); const [editingAppointment,setEditingAppointment]=useState<Appointment|null>(null); const [editOpen,setEditOpen]=useState(false); const [newOpen,setNewOpen]=useState(false); const [newDate,setNewDate]=useState<Date|null>(null); const [newTime,setNewTime]=useState('');
  useEffect(()=>{setView(isMobile?Views.DAY:Views.WEEK)},[isMobile]);
  const handleEventClick=useCallback((event:CalendarEvent)=>{setSelectedEvent(event);onEventClick?.(event)},[onEventClick]);
  const eventStyleGetter=useCallback((event:CalendarEvent)=>{const status=event.resource?.status; const palette:any={confirmed:{background:'rgba(16,185,129,.14)',border:'rgba(16,185,129,.45)',text:'#6ee7b7'},pending:{background:'rgba(245,158,11,.14)',border:'rgba(245,158,11,.45)',text:'#fcd34d'},cancelled:{background:'rgba(239,68,68,.14)',border:'rgba(239,68,68,.45)',text:'#fca5a5'},completed:{background:'rgba(139,92,246,.16)',border:'rgba(139,92,246,.48)',text:'#c4b5fd'}}; const c=palette[status]||palette.completed; return {className:`rbc-kendrah-${status||'default'}`,style:{borderRadius:'9px',opacity:1,color:c.text,backgroundColor:c.background,border:`1px solid ${c.border}`,borderLeft:`3px solid ${c.text}`,fontSize:'.82rem',fontWeight:600,padding:'4px 7px',boxShadow:'0 4px 14px rgba(0,0,0,.16)'}}},[]);
  const minTime=new Date();minTime.setHours(6,0,0,0); const maxTime=new Date();maxTime.setHours(23,0,0,0);
  const handleSlotSelect=useCallback(({start}:{start:Date;end:Date})=>{const slot=new Date(start); if(slot.getHours()<6||slot.getHours()>=23)return; const roundedMinutes=Math.round(slot.getMinutes()/30)*30; if(roundedMinutes===60) slot.setHours(slot.getHours()+1,0,0,0); else slot.setMinutes(roundedMinutes,0,0); setNewDate(slot); setNewTime(`${String(slot.getHours()).padStart(2,'0')}:${String(slot.getMinutes()).padStart(2,'0')}`); setNewOpen(true);},[]);
  const handleEdit=()=>{ if (!selectedEvent?.resource) return; setEditingAppointment(selectedEvent.resource as Appointment); setSelectedEvent(null); setEditOpen(true); };
  const handleEditOpenChange=(open:boolean)=>{setEditOpen(open); if(!open) setEditingAppointment(null);};
  const handleNewOpenChange=(open:boolean)=>{setNewOpen(open); if(!open){setNewDate(null);setNewTime('');}};
  return <><div className="mb-3 flex items-center justify-between rounded-xl border border-dashed border-kendrah-purple/30 bg-kendrah-purple/5 px-3 py-2 text-xs sm:text-sm text-muted-foreground"><span><strong className="text-kendrah-purple">Dica:</strong> clique em um horário vazio para criar um agendamento já com data e hora preenchidas.</span></div><div className="calendar-container rounded-2xl border border-white/10 bg-card shadow-2xl shadow-black/20 h-[560px] sm:h-[650px] lg:h-[720px] flex flex-col overflow-hidden"><Calendar localizer={localizer} culture="pt-BR" events={events} startAccessor="start" endAccessor="end" style={{height:'100%',minWidth:isMobile?'320px':undefined}} views={isMobile?[Views.DAY,Views.WEEK]:[Views.MONTH,Views.WEEK,Views.DAY,Views.AGENDA]} defaultView={isMobile?Views.DAY:Views.WEEK} onView={setView} view={view} date={date} onNavigate={setDate} onSelectEvent={handleEventClick} onSelectSlot={handleSlotSelect} eventPropGetter={eventStyleGetter} tooltipAccessor={(event)=>`${event.title}${event.resource?.professional_name?` • ${event.resource.professional_name}`:''}`} popup messages={messages} formats={formats} min={minTime} max={maxTime} step={30} timeslots={2} showMultiDayTimes selectable={isMobile?'ignoreEvents':true}/></div>{selectedEvent&&<AppointmentModal appointment={selectedEvent.resource} isOpen onClose={()=>setSelectedEvent(null)} onEdit={handleEdit}/>}<NewAppointmentDialog open={newOpen} onOpenChange={handleNewOpenChange} onCreated={onUpdated} initialDate={newDate} initialTime={newTime}/><NewAppointmentDialog open={editOpen} onOpenChange={handleEditOpenChange} onCreated={()=>{onUpdated?.();handleEditOpenChange(false);}} appointment={editingAppointment}/></>;
}; export default AppointmentCalendar;
