// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opqzywvuasgiyubwqtgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wcXp5d3Z1YXNnaXl1YndxdGdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4ODAwNzIsImV4cCI6MjA2MzQ1NjA3Mn0.tczJsQ_4-eDv0jdPVITs_HErO96isZ8B2yRWB-zDmbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);